import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
  variable: '--font-poppins',
});


export const metadata: Metadata = {
  title: {
    template: '%s | Wizer',
    default: 'Wizer',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`antialiased ${poppins.variable}`}>
      <body>{children}</body>
    </html>
  )
}
